// When adding a theme, make sure to add the theme here and define the colors in the CSS file!
export const THEMES = ['dark', 'light', 'CatppuccinMochaMauve', 'CatppuccinFrappeBlue', 'CatppuccinFrappeFlamingo', 'CatppuccinFrappeGreen', 'CatppuccinFrappeLavender', 'CatppuccinFrappeMaroon', 'CatppuccinFrappeMauve', 'CatppuccinFrappePeach', 'CatppuccinFrappePink', 'CatppuccinFrappeRed', 'CatppuccinFrappeRosewater', 'CatppuccinFrappeSapphire', 'CatppuccinFrappeSky', 'CatppuccinFrappeTeal', 'CatppuccinFrappeYellow', 'CatppuccinLatteBlue', 'CatppuccinLatteFlamingo', 'CatppuccinLatteGreen', 'CatppuccinLatteLavender', 'CatppuccinLatteMaroon', 'CatppuccinLatteMauve', 'CatppuccinLattePeach', 'CatppuccinLattePink', 'CatppuccinLatteRed', 'CatppuccinLatteRosewater', 'CatppuccinLatteSapphire', 'CatppuccinLatteSky', 'CatppuccinLatteTeal', 'CatppuccinLatteYellow', 'CatppuccinMacchiatoBlue', 'CatppuccinMacchiatoFlamingo', 'CatppuccinMacchiatoGreen', 'CatppuccinMacchiatoLavender', 'CatppuccinMacchiatoMaroon', 'CatppuccinMacchiatoMauve', 'CatppuccinMacchiatoPeach', 'CatppuccinMacchiatoPink', 'CatppuccinMacchiatoRed', 'CatppuccinMacchiatoRosewater', 'CatppuccinMacchiatoSapphire', 'CatppuccinMacchiatoSky', 'CatppuccinMacchiatoTeal', 'CatppuccinMacchiatoYellow', 'CatppuccinMochaBlue', 'CatppuccinMochaFlamingo', 'CatppuccinMochaGreen', 'CatppuccinMochaLavender', 'CatppuccinMochaMaroon', 'CatppuccinMochaPeach', 'CatppuccinMochaPink', 'CatppuccinMochaRed', 'CatppuccinMochaRosewater', 'CatppuccinMochaSapphire', 'CatppuccinMochaSky', 'CatppuccinMochaTeal', 'CatppuccinMochaYellow'] as const;

export const THEMABLE_PROPERTIES = [
	'clr-white',
	'clr-black',
	'clr-fg-primary',
	'clr-fg-primary-hover',
	'clr-fg-primary-pressed',
	'clr-fg-primary-disabled',
	'clr-fg-secondary',
	'clr-fg-secondary-hover',
	'clr-fg-secondary-pressed',
	'clr-fg-secondary-disabled',
	'clr-brand',
	'clr-brand-hover',
	'clr-brand-pressed',
	'clr-brand-disabled',
	'clr-onbrand',
	'clr-onbrand-hover',
	'clr-onbrand-pressed',
	'clr-onbrand-disabled',
	'clr-danger',
	'clr-danger-hover',
	'clr-danger-pressed',
	'clr-danger-disabled',
	'clr-success',
	'clr-success-hover',
	'clr-success-pressed',
	'clr-success-disabled',
	'clr-component-bg',
	'clr-component-bg-hover',
	'clr-component-bg-pressed',
	'clr-component-bg-disabled',
	'clr-code-info',
	'clr-code-warn',
	'clr-code-error',
	'clr-code-debug',
	'clr-code-trace',
	'clr-link',
	'clr-link-hover',
	'clr-link-pressed',
	'clr-link-disabled',
	'clr-page',
	'clr-page-elevated',
	'clr-page-pressed',
	'clr-secondary',
] as const;
